export enum ActionType {
    GET_SNAPSHOT = "GET_SNAPSHOT",
    GET_SNAPSHOT_SUCCESS = "GET_SNAPSHOT_SUCCESS",
    SEARCH_SNAPSHOT = "SEARCH_SNAPSHOT",
    SEARCH_SNAPSHOT_SUCCESS = "SEARCH_SNAPSHOT_SUCCESS",
    ACTION_SIGNUP = "ACTION_SIGNUP",
    ACTION_SIGNUP_SUCCESS = "ACTION_SIGNUP_SUCCESS",
    ACTION_SIGNUP_FAIL = "ACTION_SIGNUP_FAIL",
}
