export enum ActionType {
    GET_SNAPSHOT = "GET_SNAPSHOT",
    GET_SNAPSHOT_SUCCESS = "GET_SNAPSHOT_SUCCESS",
    SEARCH_SNAPSHOT = "SEARCH_SNAPSHOT",
    SEARCH_SNAPSHOT_SUCCESS = "SEARCH_SNAPSHOT_SUCCESS",
    ACTION_SIGNUP = "ACTION_SIGNUP",
    ACTION_SIGNUP_SUCCESS = "ACTION_SIGNUP_SUCCESS",
    ACTION_SIGNUP_FAIL = "ACTION_SIGNUP_FAIL",
    UPLOAD_SNAPSHOT = "UPLOAD_SNAPSHOT",
    UPLOAD_SNAPSHOT_LOADING = "UPLOAD_SNAPSHOT_LOADING",
    UPLOAD_SNAPSHOT_SUCCESS = "UPLOAD_SNAPSHOT_SUCCESS",
    UPLOAD_SNAPSHOT_FAIL = "UPLOAD_SNAPSHOT_FAIL",
    REMOVE_SNAPSHOT = "REMOVE_SNAPSHOT",
    REMOVE_SNAPSHOT_SUCCESS = "REMOVE_SNAPSHOT_SUCCESS",
    REMOVE_SNAPSHOT_LOADING = "REMOVE_SNAPSHOT_LOADING",
    REMOVE_SNAPSHOT_FAIL = "REMOVE_SNAPSHOT_FAIL"
}
